//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _190413_ProjeV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MakaleResimleri
    {
        public int MakaleResimleriID { get; set; }
        public string BuyukResim { get; set; }
        public string OrtaResim { get; set; }
        public string KucukResim { get; set; }
        public Nullable<int> MakaleID { get; set; }
    
        public virtual Makaleler Makaleler { get; set; }
    }
}
